name: C++ Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get install -y g++
      - name: Build
        run: g++ -o neural_network main.cpp neural_network.cpp
      - name: Run
        run: ./neural_network
      - name: Run tests
        run: ./test_neural_network